version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.14.0-europium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome-debug:3.14.0-europium
    container_name: selenium-node-chrome
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox-debug:3.14.0-europium
    container_name: selenium-node-firefox
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
